
import andius.Andius;
import andius.Constants;
import andius.Context;
import andius.EquipmentScreen;
import static andius.WizardryData.PMO_ITEMS_MAP;
import andius.objects.ClassType;
import andius.objects.SaveGame;
import andius.objects.SaveGame.CharacterRecord;
import andius.objects.Spells;
import com.badlogic.gdx.Game;
import com.badlogic.gdx.backends.lwjgl.LwjglApplication;
import com.badlogic.gdx.backends.lwjgl.LwjglApplicationConfiguration;
import utils.Utils;

public class Wiz4CombatTestMain extends Game {

    public static void main(String[] args) {
        LwjglApplicationConfiguration cfg = new LwjglApplicationConfiguration();
        cfg.title = "Wiz4CombatTestMain";
        cfg.width = 1024;
        cfg.height = 768;
        new LwjglApplication(new Wiz4CombatTestMain(), cfg);
    }

    @Override
    public void create() {

        try {

            Andius a = new Andius();
            a.create();

            Context ctx = new Context();
            //SaveGame sg = SaveGame.read(SAVE_FILENAME);
            //ctx.setSaveGame(sg);
            ctx.setSaveGame(new SaveGame());
            ctx.saveGame.players = new CharacterRecord[6];
            if (true) {
                for (int j = 0; j < ctx.saveGame.players.length; j++) {
                    ctx.saveGame.players[j] = new CharacterRecord();
                    ctx.saveGame.players[j].name = "player" + j;
                    ctx.saveGame.players[j].classType = ClassType.values()[Utils.getRandomBetween(0,7)];
                    int lvl = Utils.getRandomBetween(1,7);
                    ctx.saveGame.players[j].level = lvl;
                    ctx.saveGame.players[j].hp = 12 * lvl;
                    ctx.saveGame.players[j].maxhp = 12 * lvl;
                    ctx.saveGame.players[j].gold = 3000;

                    ctx.saveGame.players[j].str = Utils.getRandomBetween(10,17);
                    ctx.saveGame.players[j].intell = Utils.getRandomBetween(10,17);
                    ctx.saveGame.players[j].piety = Utils.getRandomBetween(10,17);
                    ctx.saveGame.players[j].vitality = Utils.getRandomBetween(10,17);
                    ctx.saveGame.players[j].agility = Utils.getRandomBetween(10,17);
                    ctx.saveGame.players[j].luck = Utils.getRandomBetween(10,17);

                    ctx.saveGame.players[j].armor = PMO_ITEMS_MAP.get("ROBES");
                    ctx.saveGame.players[j].weapon = PMO_ITEMS_MAP.get("STAFF");
                    //ctx.saveGame.players[j].weapon = PMO_ITEMS_MAP.get("MAGIC BOW");
                    //ctx.saveGame.players[j].helm = PMO_ITEMS_MAP.get("HELM");
                    //ctx.saveGame.players[j].shield = PMO_ITEMS_MAP.get("LARGE SHIELD");
                    //ctx.saveGame.players[j].glove = PMO_ITEMS_MAP.get("SILVER GLOVES");
                    //ctx.saveGame.players[j].item1 = PMO_ITEMS_MAP.get("ROD OF FLAME");
                    //ctx.saveGame.players[j].item2 = PMO_ITEMS_MAP.get("WERDNAS AMULET");

                    ctx.saveGame.players[j].magePoints = new int[]{5, 5, 5, 5, 5, 5, 5};
                    ctx.saveGame.players[j].clericPoints = new int[]{5, 5, 5, 5, 5, 5, 5};

                    for (Spells s : Spells.values()) {
                        ctx.saveGame.players[j].knownSpells.add(s);
                    }

                }
            }

            //ctx.players()[0].inventory.add(WER_ITEMS.get(7));
//            List<MutableMonster> mms = new ArrayList<>();
//            mms.add(new MutableMonster(PMO_MONSTERS.get(3)));
//            mms.add(new MutableMonster(PMO_MONSTERS.get(3)));
//            mms.add(new MutableMonster(PMO_MONSTERS.get(3)));
//            mms.add(new MutableMonster(PMO_MONSTERS.get(4)));
//            mms.add(new MutableMonster(PMO_MONSTERS.get(4)));
//            mms.add(new MutableMonster(PMO_MONSTERS.get(4)));
//            mms.add(new MutableMonster(PMO_MONSTERS.get(6)));
//            mms.add(new MutableMonster(PMO_MONSTERS.get(6)));
//            mms.add(new MutableMonster(PMO_MONSTERS.get(6)));
//            TextureAtlas iconAtlas = new TextureAtlas(Gdx.files.classpath("assets/json/wiz4ibm.atlas"));
//            Map<Integer, String> icons = new HashMap<>();
//            for (DoGooder dg : WER4_CHARS) {
//                icons.put(dg.id, dg.iconID);
//            }
//
//            GsonBuilder builder = new GsonBuilder();
//            Gson gson = builder.setPrettyPrinting().create();
//            String json = gson.toJson(icons);
//            System.out.println(json);
//            Map<Integer, String> icons = gson.fromJson(ICON_JSON, new TypeToken<Map<Integer, String>>() {
//            }.getType());
//
//            for (DoGooder dg : WER4_CHARS) {
//                dg.iconID = icons.get(dg.id);
//            }
//
//            String json = gson.toJson(WER4_CHARS);
//            System.out.println(json);
            //setScreen(new Wiz4CombatScreen(ctx.saveGame.players[0], ctx.saveGame.players[0].summonedMonsters, WER4_CHARS.get(442), null, null));
            //setScreen(new WizardryCombatScreen(ctx, Constants.Map.WIZARDRY1, PMO_MONSTERS.get(9), 1, true, null, null));
            //setScreen(new Wiz4RewardScreen(ctx.saveGame.players[0], WER4_CHARS.get(0)));
            setScreen(new EquipmentScreen(ctx, Constants.Map.WORLD));
            //setScreen(new Wiz4RewardScreen(ctx.saveGame.players[0], WER4_CHARS.get(180)));
            //setScreen(new RewardScreen(ctx, Constants.Map.WORLD, 1, 0, 5));
            //setScreen(new VendorScreen(ctx, Role.MERCHANT2, Constants.Map.CAVE, "paul"));
            //setScreen(new SummoningCircleScreen(ctx.saveGame.players[0], SummoningCircle.CIRCLE1));

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private static final String ICON_JSON = "{\n"
            + "  \"0\": \"mag1\",\n"
            + "  \"1\": \"fig1\",\n"
            + "  \"2\": \"lor1\",\n"
            + "  \"3\": \"sam1\",\n"
            + "  \"4\": \"thi1\",\n"
            + "  \"5\": \"pri2\",\n"
            + "  \"6\": \"mag2\",\n"
            + "  \"7\": \"bis2\",\n"
            + "  \"8\": \"pri2\",\n"
            + "  \"9\": \"pri2\",\n"
            + "  \"10\": \"sam2\",\n"
            + "  \"11\": \"lor2\",\n"
            + "  \"12\": \"mag2\",\n"
            + "  \"13\": \"thi3\",\n"
            + "  \"14\": \"lor3\",\n"
            + "  \"15\": \"sam3\",\n"
            + "  \"16\": \"pri3\",\n"
            + "  \"17\": \"lor3\",\n"
            + "  \"18\": \"nin2\",\n"
            + "  \"19\": \"bis3\",\n"
            + "  \"20\": \"fig1\",\n"
            + "  \"21\": \"thi1\",\n"
            + "  \"22\": \"fig1\",\n"
            + "  \"23\": \"fig1\",\n"
            + "  \"24\": \"fig1\",\n"
            + "  \"25\": \"fig1\",\n"
            + "  \"26\": \"fig1\",\n"
            + "  \"27\": \"fig1\",\n"
            + "  \"28\": \"fig1\",\n"
            + "  \"29\": \"thi1\",\n"
            + "  \"30\": \"thi1\",\n"
            + "  \"31\": \"mag1\",\n"
            + "  \"32\": \"mag1\",\n"
            + "  \"33\": \"pri1\",\n"
            + "  \"34\": \"pri1\",\n"
            + "  \"35\": \"fig1\",\n"
            + "  \"36\": \"fig1\",\n"
            + "  \"37\": \"sam1\",\n"
            + "  \"38\": \"bis1\",\n"
            + "  \"39\": \"bis1\",\n"
            + "  \"40\": \"thi1\",\n"
            + "  \"41\": \"fig1\",\n"
            + "  \"42\": \"fig1\",\n"
            + "  \"43\": \"fig1\",\n"
            + "  \"44\": \"fig1\",\n"
            + "  \"45\": \"fig1\",\n"
            + "  \"46\": \"fig1\",\n"
            + "  \"47\": \"fig1\",\n"
            + "  \"48\": \"fig1\",\n"
            + "  \"49\": \"mag1\",\n"
            + "  \"50\": \"mag1\",\n"
            + "  \"51\": \"pri1\",\n"
            + "  \"52\": \"pri1\",\n"
            + "  \"53\": \"thi1\",\n"
            + "  \"54\": \"thi1\",\n"
            + "  \"55\": \"fig1\",\n"
            + "  \"56\": \"bis1\",\n"
            + "  \"57\": \"bis1\",\n"
            + "  \"58\": \"bis1\",\n"
            + "  \"59\": \"sam1\",\n"
            + "  \"60\": \"bis1\",\n"
            + "  \"61\": \"fig1\",\n"
            + "  \"62\": \"bis1\",\n"
            + "  \"63\": \"fig1\",\n"
            + "  \"64\": \"fig1\",\n"
            + "  \"65\": \"fig1\",\n"
            + "  \"66\": \"fig1\",\n"
            + "  \"67\": \"fig1\",\n"
            + "  \"68\": \"fig1\",\n"
            + "  \"69\": \"mag1\",\n"
            + "  \"70\": \"mag1\",\n"
            + "  \"71\": \"pri1\",\n"
            + "  \"72\": \"fig1\",\n"
            + "  \"73\": \"thi1\",\n"
            + "  \"74\": \"thi1\",\n"
            + "  \"75\": \"sam1\",\n"
            + "  \"76\": \"bis1\",\n"
            + "  \"77\": \"bis1\",\n"
            + "  \"78\": \"lor1\",\n"
            + "  \"79\": \"mag1\",\n"
            + "  \"80\": \"fig2\",\n"
            + "  \"81\": \"bis2\",\n"
            + "  \"82\": \"fig2\",\n"
            + "  \"83\": \"fig2\",\n"
            + "  \"84\": \"fig2\",\n"
            + "  \"85\": \"fig2\",\n"
            + "  \"86\": \"fig2\",\n"
            + "  \"87\": \"fig2\",\n"
            + "  \"88\": \"fig2\",\n"
            + "  \"89\": \"mag2\",\n"
            + "  \"90\": \"mag2\",\n"
            + "  \"91\": \"mag2\",\n"
            + "  \"92\": \"mag2\",\n"
            + "  \"93\": \"nin1\",\n"
            + "  \"94\": \"pri2\",\n"
            + "  \"95\": \"bis2\",\n"
            + "  \"96\": \"fig2\",\n"
            + "  \"97\": \"mag2\",\n"
            + "  \"98\": \"mag2\",\n"
            + "  \"99\": \"mag2\",\n"
            + "  \"100\": \"thi2\",\n"
            + "  \"101\": \"thi2\",\n"
            + "  \"102\": \"fig2\",\n"
            + "  \"103\": \"fig2\",\n"
            + "  \"104\": \"fig2\",\n"
            + "  \"105\": \"fig2\",\n"
            + "  \"106\": \"fig2\",\n"
            + "  \"107\": \"fig2\",\n"
            + "  \"108\": \"fig2\",\n"
            + "  \"109\": \"mag2\",\n"
            + "  \"110\": \"mag2\",\n"
            + "  \"111\": \"thi2\",\n"
            + "  \"112\": \"bis2\",\n"
            + "  \"113\": \"fig2\",\n"
            + "  \"114\": \"nin1\",\n"
            + "  \"115\": \"bis2\",\n"
            + "  \"116\": \"bis2\",\n"
            + "  \"117\": \"fig2\",\n"
            + "  \"118\": \"sam2\",\n"
            + "  \"119\": \"lor2\",\n"
            + "  \"120\": \"thi2\",\n"
            + "  \"121\": \"pri2\",\n"
            + "  \"122\": \"fig2\",\n"
            + "  \"123\": \"fig2\",\n"
            + "  \"124\": \"bis2\",\n"
            + "  \"125\": \"mag2\",\n"
            + "  \"126\": \"mag2\",\n"
            + "  \"127\": \"pri2\",\n"
            + "  \"128\": \"thi2\",\n"
            + "  \"129\": \"thi2\",\n"
            + "  \"130\": \"sam2\",\n"
            + "  \"131\": \"nin1\",\n"
            + "  \"132\": \"mag2\",\n"
            + "  \"133\": \"pri2\",\n"
            + "  \"134\": \"thi2\",\n"
            + "  \"135\": \"nin1\",\n"
            + "  \"136\": \"bis2\",\n"
            + "  \"137\": \"thi2\",\n"
            + "  \"138\": \"thi2\",\n"
            + "  \"139\": \"bis2\",\n"
            + "  \"140\": \"thi2\",\n"
            + "  \"141\": \"thi3\",\n"
            + "  \"142\": \"fig2\",\n"
            + "  \"143\": \"sam3\",\n"
            + "  \"144\": \"fig3\",\n"
            + "  \"145\": \"fig3\",\n"
            + "  \"146\": \"mag3\",\n"
            + "  \"147\": \"mag3\",\n"
            + "  \"148\": \"pri3\",\n"
            + "  \"149\": \"thi3\",\n"
            + "  \"150\": \"nin2\",\n"
            + "  \"151\": \"fig2\",\n"
            + "  \"152\": \"bis2\",\n"
            + "  \"153\": \"mag2\",\n"
            + "  \"154\": \"nin2\",\n"
            + "  \"155\": \"mag2\",\n"
            + "  \"156\": \"bis3\",\n"
            + "  \"157\": \"bis3\",\n"
            + "  \"158\": \"fig3\",\n"
            + "  \"159\": \"fig3\",\n"
            + "  \"160\": \"thi3\",\n"
            + "  \"161\": \"thi3\",\n"
            + "  \"162\": \"pri3\",\n"
            + "  \"163\": \"thi3\",\n"
            + "  \"164\": \"thi3\",\n"
            + "  \"165\": \"thi3\",\n"
            + "  \"166\": \"bis3\",\n"
            + "  \"167\": \"bis3\",\n"
            + "  \"168\": \"sam3\",\n"
            + "  \"169\": \"fig3\",\n"
            + "  \"170\": \"fig3\",\n"
            + "  \"171\": \"fig3\",\n"
            + "  \"172\": \"fig3\",\n"
            + "  \"173\": \"fig3\",\n"
            + "  \"174\": \"lor3\",\n"
            + "  \"175\": \"sam3\",\n"
            + "  \"176\": \"pri3\",\n"
            + "  \"177\": \"fig3\",\n"
            + "  \"178\": \"mag3\",\n"
            + "  \"179\": \"mag3\",\n"
            + "  \"180\": \"bis3\",\n"
            + "  \"181\": \"thi3\",\n"
            + "  \"182\": \"pri3\",\n"
            + "  \"183\": \"pri3\",\n"
            + "  \"184\": \"pri3\",\n"
            + "  \"185\": \"thi3\",\n"
            + "  \"186\": \"thi3\",\n"
            + "  \"187\": \"sam3\",\n"
            + "  \"188\": \"nin2\",\n"
            + "  \"189\": \"nin2\",\n"
            + "  \"190\": \"nin2\",\n"
            + "  \"191\": \"fig3\",\n"
            + "  \"192\": \"fig3\",\n"
            + "  \"193\": \"lor3\",\n"
            + "  \"194\": \"fig3\",\n"
            + "  \"195\": \"bis3\",\n"
            + "  \"196\": \"fig3\",\n"
            + "  \"197\": \"fig3\",\n"
            + "  \"198\": \"fig3\",\n"
            + "  \"199\": \"mag3\",\n"
            + "  \"200\": \"thi3\",\n"
            + "  \"201\": \"fig3\",\n"
            + "  \"202\": \"pri3\",\n"
            + "  \"203\": \"pri3\",\n"
            + "  \"204\": \"pri3\",\n"
            + "  \"205\": \"thi3\",\n"
            + "  \"206\": \"bis3\",\n"
            + "  \"207\": \"mag3\",\n"
            + "  \"208\": \"pri3\",\n"
            + "  \"209\": \"pri3\",\n"
            + "  \"210\": \"thi3\",\n"
            + "  \"211\": \"thi3\",\n"
            + "  \"212\": \"bis3\",\n"
            + "  \"213\": \"bis3\",\n"
            + "  \"214\": \"sam3\",\n"
            + "  \"215\": \"bis3\",\n"
            + "  \"216\": \"pri3\",\n"
            + "  \"217\": \"sam3\",\n"
            + "  \"218\": \"sam3\",\n"
            + "  \"219\": \"lor3\",\n"
            + "  \"220\": \"pri3\",\n"
            + "  \"221\": \"pri3\",\n"
            + "  \"222\": \"thi3\",\n"
            + "  \"223\": \"bis3\",\n"
            + "  \"224\": \"bis3\",\n"
            + "  \"225\": \"bis3\",\n"
            + "  \"226\": \"bis3\",\n"
            + "  \"227\": \"bis3\",\n"
            + "  \"228\": \"bis3\",\n"
            + "  \"229\": \"pri3\",\n"
            + "  \"230\": \"bis3\",\n"
            + "  \"231\": \"nin2\",\n"
            + "  \"232\": \"sam3\",\n"
            + "  \"233\": \"nin3\",\n"
            + "  \"234\": \"nin2\",\n"
            + "  \"235\": \"thi3\",\n"
            + "  \"236\": \"sam3\",\n"
            + "  \"237\": \"lor3\",\n"
            + "  \"238\": \"fig3\",\n"
            + "  \"239\": \"nin2\",\n"
            + "  \"240\": \"sam1\",\n"
            + "  \"241\": \"fig1\",\n"
            + "  \"242\": \"mag1\",\n"
            + "  \"243\": \"fig1\",\n"
            + "  \"244\": \"pri1\",\n"
            + "  \"245\": \"mag1\",\n"
            + "  \"246\": \"mag1\",\n"
            + "  \"247\": \"fig1\",\n"
            + "  \"248\": \"fig1\",\n"
            + "  \"249\": \"mag1\",\n"
            + "  \"250\": \"fig1\",\n"
            + "  \"251\": \"mag1\",\n"
            + "  \"252\": \"mag1\",\n"
            + "  \"253\": \"fig1\",\n"
            + "  \"254\": \"pri1\",\n"
            + "  \"255\": \"fig1\",\n"
            + "  \"256\": \"fig1\",\n"
            + "  \"257\": \"fig1\",\n"
            + "  \"258\": \"pri2\",\n"
            + "  \"259\": \"fig2\",\n"
            + "  \"260\": \"sam2\",\n"
            + "  \"261\": \"fig2\",\n"
            + "  \"262\": \"mag2\",\n"
            + "  \"263\": \"sam2\",\n"
            + "  \"264\": \"sam2\",\n"
            + "  \"265\": \"bis2\",\n"
            + "  \"266\": \"mag2\",\n"
            + "  \"267\": \"fig2\",\n"
            + "  \"268\": \"nin1\",\n"
            + "  \"269\": \"sam2\",\n"
            + "  \"270\": \"pri2\",\n"
            + "  \"271\": \"fig2\",\n"
            + "  \"272\": \"mag2\",\n"
            + "  \"273\": \"lor2\",\n"
            + "  \"274\": \"lor2\",\n"
            + "  \"275\": \"pri2\",\n"
            + "  \"276\": \"pri2\",\n"
            + "  \"277\": \"fig2\",\n"
            + "  \"278\": \"fig2\",\n"
            + "  \"279\": \"mag2\",\n"
            + "  \"280\": \"pri3\",\n"
            + "  \"281\": \"mag3\",\n"
            + "  \"282\": \"lor3\",\n"
            + "  \"283\": \"mag3\",\n"
            + "  \"284\": \"bis3\",\n"
            + "  \"285\": \"nin2\",\n"
            + "  \"286\": \"nin2\",\n"
            + "  \"287\": \"fig3\",\n"
            + "  \"288\": \"lor3\",\n"
            + "  \"289\": \"mag3\",\n"
            + "  \"290\": \"lor3\",\n"
            + "  \"291\": \"nin2\",\n"
            + "  \"292\": \"pri3\",\n"
            + "  \"293\": \"fig3\",\n"
            + "  \"294\": \"nin2\",\n"
            + "  \"295\": \"fig3\",\n"
            + "  \"296\": \"pri3\",\n"
            + "  \"297\": \"lor3\",\n"
            + "  \"298\": \"lor3\",\n"
            + "  \"299\": \"mag3\",\n"
            + "  \"300\": \"sam3\",\n"
            + "  \"301\": \"mag3\",\n"
            + "  \"302\": \"fig3\",\n"
            + "  \"303\": \"fig3\",\n"
            + "  \"304\": \"bis3\",\n"
            + "  \"305\": \"fig3\",\n"
            + "  \"306\": \"sam3\",\n"
            + "  \"307\": \"sam2\",\n"
            + "  \"308\": \"lor3\",\n"
            + "  \"309\": \"lor3\",\n"
            + "  \"310\": \"lor3\",\n"
            + "  \"311\": \"nin2\",\n"
            + "  \"312\": \"fig3\",\n"
            + "  \"313\": \"fig3\",\n"
            + "  \"314\": \"thi3\",\n"
            + "  \"315\": \"lor3\",\n"
            + "  \"316\": \"nin2\",\n"
            + "  \"317\": \"fig3\",\n"
            + "  \"318\": \"fig3\",\n"
            + "  \"319\": \"fig3\",\n"
            + "  \"320\": \"mag3\",\n"
            + "  \"321\": \"pri3\",\n"
            + "  \"322\": \"pri3\",\n"
            + "  \"323\": \"pri3\",\n"
            + "  \"324\": \"mag2\",\n"
            + "  \"325\": \"mag3\",\n"
            + "  \"326\": \"mag3\",\n"
            + "  \"327\": \"thi3\",\n"
            + "  \"328\": \"thi3\",\n"
            + "  \"329\": \"bis3\",\n"
            + "  \"330\": \"sam3\",\n"
            + "  \"331\": \"lor3\",\n"
            + "  \"332\": \"nin2\",\n"
            + "  \"333\": \"nin2\",\n"
            + "  \"334\": \"nin2\",\n"
            + "  \"335\": \"nin2\",\n"
            + "  \"336\": \"nin2\",\n"
            + "  \"337\": \"mag2\",\n"
            + "  \"338\": \"pri3\",\n"
            + "  \"339\": \"thi3\",\n"
            + "  \"340\": \"thi3\",\n"
            + "  \"341\": \"bis3\",\n"
            + "  \"342\": \"lor3\",\n"
            + "  \"343\": \"nin2\",\n"
            + "  \"344\": \"nin2\",\n"
            + "  \"345\": \"mag3\",\n"
            + "  \"346\": \"pri3\",\n"
            + "  \"347\": \"sam3\",\n"
            + "  \"348\": \"thi3\",\n"
            + "  \"349\": \"nin2\",\n"
            + "  \"350\": \"guard\",\n"
            + "  \"351\": \"guard\",\n"
            + "  \"352\": \"guard\",\n"
            + "  \"353\": \"guard\",\n"
            + "  \"354\": \"private\",\n"
            + "  \"355\": \"private\",\n"
            + "  \"356\": \"private\",\n"
            + "  \"357\": \"private\",\n"
            + "  \"358\": \"private\",\n"
            + "  \"359\": \"corpo\",\n"
            + "  \"360\": \"corpo\",\n"
            + "  \"361\": \"corpo\",\n"
            + "  \"362\": \"corpo\",\n"
            + "  \"363\": \"corpo\",\n"
            + "  \"364\": \"corpo\",\n"
            + "  \"365\": \"serge\",\n"
            + "  \"366\": \"lieut\",\n"
            + "  \"367\": \"lieut\",\n"
            + "  \"368\": \"lieut\",\n"
            + "  \"369\": \"lieut\",\n"
            + "  \"370\": \"lieut\",\n"
            + "  \"371\": \"captain\",\n"
            + "  \"372\": \"dog\",\n"
            + "  \"373\": \"puppy\",\n"
            + "  \"374\": \"golem\",\n"
            + "  \"375\": \"glum\",\n"
            + "  \"376\": \"dream\",\n"
            + "  \"377\": \"mag2\",\n"
            + "  \"378\": \"senti\",\n"
            + "  \"379\": \"butt1\",\n"
            + "  \"380\": \"butt1\",\n"
            + "  \"381\": \"butt1\",\n"
            + "  \"382\": \"butt1\",\n"
            + "  \"383\": \"lor2\",\n"
            + "  \"384\": \"butt2\",\n"
            + "  \"385\": \"butt2\",\n"
            + "  \"386\": \"butt2\",\n"
            + "  \"387\": \"butt2\",\n"
            + "  \"388\": \"butt2\",\n"
            + "  \"389\": \"butt1\",\n"
            + "  \"390\": \"t_1\",\n"
            + "  \"391\": \"t_1\",\n"
            + "  \"392\": \"t_1\",\n"
            + "  \"393\": \"t_1\",\n"
            + "  \"394\": \"t_1\",\n"
            + "  \"395\": \"t_1\",\n"
            + "  \"396\": \"t_1\",\n"
            + "  \"397\": \"t_1\",\n"
            + "  \"398\": \"t_1\",\n"
            + "  \"399\": \"t_1\",\n"
            + "  \"400\": \"t_1\",\n"
            + "  \"401\": \"t_1\",\n"
            + "  \"402\": \"t_1\",\n"
            + "  \"403\": \"t_1\",\n"
            + "  \"404\": \"t_1\",\n"
            + "  \"405\": \"t_1\",\n"
            + "  \"406\": \"t_1\",\n"
            + "  \"407\": \"t_1\",\n"
            + "  \"408\": \"fig3\",\n"
            + "  \"409\": \"mag3\",\n"
            + "  \"410\": \"nin2\",\n"
            + "  \"411\": \"pri3\",\n"
            + "  \"412\": \"pri1\",\n"
            + "  \"413\": \"fig3\",\n"
            + "  \"414\": \"sam1\",\n"
            + "  \"415\": \"sam2\",\n"
            + "  \"416\": \"mag2\",\n"
            + "  \"417\": \"lor3\",\n"
            + "  \"418\": \"rose\",\n"
            + "  \"419\": \"rose\",\n"
            + "  \"420\": \"rose\",\n"
            + "  \"421\": \"rose\",\n"
            + "  \"422\": \"rose\",\n"
            + "  \"423\": \"rose\",\n"
            + "  \"424\": \"pelican\",\n"
            + "  \"425\": \"pelican\",\n"
            + "  \"426\": \"pelican\",\n"
            + "  \"427\": \"pelican\",\n"
            + "  \"428\": \"pelican\",\n"
            + "  \"429\": \"pelican\",\n"
            + "  \"430\": \"laurel\",\n"
            + "  \"431\": \"laurel\",\n"
            + "  \"432\": \"laurel\",\n"
            + "  \"433\": \"laurel\",\n"
            + "  \"434\": \"laurel\",\n"
            + "  \"435\": \"laurel\",\n"
            + "  \"436\": \"tiger\",\n"
            + "  \"437\": \"tiger\",\n"
            + "  \"438\": \"tiger\",\n"
            + "  \"439\": \"tiger\",\n"
            + "  \"440\": \"tiger\",\n"
            + "  \"441\": \"tiger\",\n"
            + "  \"442\": \"t_2\",\n"
            + "  \"443\": \"t_2\",\n"
            + "  \"444\": \"t_2\",\n"
            + "  \"445\": \"t_2\",\n"
            + "  \"446\": \"t_2\",\n"
            + "  \"447\": \"t_2\",\n"
            + "  \"448\": \"softalk\",\n"
            + "  \"449\": \"softalk\",\n"
            + "  \"450\": \"softalk\",\n"
            + "  \"451\": \"softalk\",\n"
            + "  \"452\": \"softalk\",\n"
            + "  \"453\": \"fig1\",\n"
            + "  \"454\": \"mag1\",\n"
            + "  \"455\": \"thi3\",\n"
            + "  \"456\": \"pri3\",\n"
            + "  \"457\": \"mag2\",\n"
            + "  \"458\": \"nin2\",\n"
            + "  \"459\": \"pri2\",\n"
            + "  \"460\": \"baron\",\n"
            + "  \"461\": \"baron\",\n"
            + "  \"462\": \"baron\",\n"
            + "  \"463\": \"baron\",\n"
            + "  \"464\": \"baron\",\n"
            + "  \"465\": \"baron\",\n"
            + "  \"466\": \"duke\",\n"
            + "  \"467\": \"duke\",\n"
            + "  \"468\": \"duke\",\n"
            + "  \"469\": \"duke\",\n"
            + "  \"470\": \"duke\",\n"
            + "  \"471\": \"duke\",\n"
            + "  \"472\": \"private\",\n"
            + "  \"473\": \"bis2\",\n"
            + "  \"474\": \"corpo\",\n"
            + "  \"475\": \"corpo\",\n"
            + "  \"476\": \"corpo\",\n"
            + "  \"477\": \"corpo\",\n"
            + "  \"478\": \"corpo\",\n"
            + "  \"479\": \"captain\",\n"
            + "  \"480\": \"serge\",\n"
            + "  \"481\": \"serge\",\n"
            + "  \"482\": \"serge\",\n"
            + "  \"483\": \"serge\",\n"
            + "  \"484\": \"serge\",\n"
            + "  \"485\": \"serge\",\n"
            + "  \"486\": \"nin2\",\n"
            + "  \"487\": \"pri3\",\n"
            + "  \"488\": \"pri3\",\n"
            + "  \"489\": \"pri3\",\n"
            + "  \"490\": \"pri3\",\n"
            + "  \"491\": \"pri3\",\n"
            + "  \"492\": \"pri3\",\n"
            + "  \"493\": \"fig3\",\n"
            + "  \"494\": \"fig3\",\n"
            + "  \"495\": \"pri3\",\n"
            + "  \"496\": \"pri3\",\n"
            + "  \"497\": \"pri3\",\n"
            + "  \"498\": \"bis3\",\n"
            + "  \"499\": \"hawk\"\n"
            + "}";

}
